### ISSUE TITLE
Error on rule decompose step !! 

### ISSUE THREAD

**Issue by vinayrajput0005** [rvalieris/LCS#14]
(lcs) test@NCIM-Workstation2:/data/Student_Data/LCS-master$ snakemake --config markers=pango dataset=mypool --cores 70 --resources mem_gb=200
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 70
Rules claiming more threads will be scaled down.
Provided resources: mem_gb=200
Job stats:
job          count    min threads    max threads
---------  -------  -------------  -------------
all              1              1              1
decompose        1             50             50
total            2              1             50

Select jobs to execute...

[Wed Nov 30 19:15:17 2022]
rule decompose:
    input: outputs/variants_table/pango-markers-table.tsv, outputs/variants_table/pool_samples_mypool.tsv
    output: outputs/decompose/mypool.status, outputs/decompose/mypool.out
    jobid: 1
    reason: Missing output files: outputs/decompose/mypool.out
    threads: 50
    resources: tmpdir=/tmp, mem_gb=160

using 285 markers to estimate 22 variant groups
(solve pid=1333588) WARNING - large complementary slackness residual: 0.025679
(solve pid=1334345) WARNING - large complementary slackness residual: 0.033062
Traceback (most recent call last):
  File "/data/Student_Data/Vinay/LCS-master/scripts/vg-decompose.py", line 185, in <module>
    main()
  File "/data/Student_Data/Vinay/LCS-master/scripts/vg-decompose.py", line 182, in main
    solve_samples(markers_df, pools, marker_snps_list, tags, pool_tags)
  File "/data/Student_Data/Vinay/LCS-master/scripts/vg-decompose.py", line 129, in solve_samples
    prob, result, x = ray.get(wid)
  File "/home/test/anaconda3/envs/lcs/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/test/anaconda3/envs/lcs/lib/python3.9/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::solve() (pid=1341823, ip=172.28.28.88)
  File "/data/Student_Data/Vinay/LCS-master/scripts/vg-decompose.py", line 45, in solve
    objective = cvxpy.Minimize(negLLH(x, vs, ps_m, ps_dp - ps_m))
  File "/data/Student_Data/Vinay/LCS-master/scripts/vg-decompose.py", line 33, in negLLH
    ps = cvxpy.matmul(vars_snps, f)
  File "/home/test/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/atoms/affine/binary_operators.py", line 86, in matmul
    return MulExpression(lh_exp, rh_exp)
  File "/home/test/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/atoms/affine/binary_operators.py", line 50, in __init__
    super(BinaryOperator, self).__init__(lh_exp, rh_exp)
  File "/home/test/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/atoms/atom.py", line 49, in __init__
    self.args = [Atom.cast_to_const(arg) for arg in args]
  File "/home/test/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/atoms/atom.py", line 49, in <listcomp>
    self.args = [Atom.cast_to_const(arg) for arg in args]
  File "/home/test/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/expressions/expression.py", line 507, in cast_to_const
    return expr if isinstance(expr, Expression) else cvxtypes.constant()(expr)
  File "/home/test/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/expressions/constants/constant.py", line 58, in __init__
    super(Constant, self).__init__(intf.shape(self.value))
  File "/home/test/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/expressions/leaf.py", line 108, in __init__
    raise ValueError("Invalid dimensions %s." % (shape,))
ValueError: Invalid dimensions (0, 22).
[Wed Nov 30 19:18:09 2022]
Error in rule decompose:
    jobid: 1
    output: outputs/decompose/mypool.status, outputs/decompose/mypool.out
    shell:
        python scripts/vg-decompose.py -m outputs/variants_table/pango-markers-table.tsv -p outputs/variants_table/pool_samples_mypool.tsv -o outputs/decompose/mypool.out -s outputs/decompose/mypool.status --threads 50
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job decompose since they might be corrupted:
outputs/decompose/mypool.status, outputs/decompose/mypool.out
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-11-30T191514.901726.snakemake.log
(lcs) test@NCIM-Workstation2:/data/Student_Data/Vinay/LCS-master$

**Comment by rvalieris** [comment]
hello, looks like either the markers on the pools data could have some missing values or zero values that resulted in this error, can you check the `outputs/variants_table/pango-markers-table.tsv` and `outputs/variants_table/pool_samples_mypool.tsv` files and make sure the data looks good ? alternatively if possible, can you send me the files I can check this.
