### ISSUE TITLE
Error in procesing the samples ... 

### ISSUE THREAD

**Issue by vinayrajput0005** [rvalieris/LCS#18]
warning: dropping 11 markers because they are not present on the pools
using 284 markers to estimate 29 variant groups
Traceback (most recent call last):
  File "/media/ncim/Expansion/vinay_Data_Workstation1/software/MULTIPLE_LCS/LCS-master_03/scripts/vg-decompose.py", line 185, in <module>
    main()
  File "/media/ncim/Expansion/vinay_Data_Workstation1/software/MULTIPLE_LCS/LCS-master_03/scripts/vg-decompose.py", line 182, in main
    solve_samples(markers_df, pools, marker_snps_list, tags, pool_tags)
  File "/media/ncim/Expansion/vinay_Data_Workstation1/software/MULTIPLE_LCS/LCS-master_03/scripts/vg-decompose.py", line 129, in solve_samples
    prob, result, x = ray.get(wid)
  File "/home/ncim/anaconda3/envs/lcs/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ncim/anaconda3/envs/lcs/lib/python3.9/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::solve() (pid=33388, ip=172.28.28.66)
  File "/media/ncim/Expansion/vinay_Data_Workstation1/software/MULTIPLE_LCS/LCS-master_03/scripts/vg-decompose.py", line 45, in solve
    objective = cvxpy.Minimize(negLLH(x, vs, ps_m, ps_dp - ps_m))
  File "/media/ncim/Expansion/vinay_Data_Workstation1/software/MULTIPLE_LCS/LCS-master_03/scripts/vg-decompose.py", line 33, in negLLH
    ps = cvxpy.matmul(vars_snps, f)
  File "/home/ncim/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/atoms/affine/binary_operators.py", line 86, in matmul
    return MulExpression(lh_exp, rh_exp)
  File "/home/ncim/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/atoms/affine/binary_operators.py", line 50, in __init__
    super(BinaryOperator, self).__init__(lh_exp, rh_exp)
  File "/home/ncim/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/atoms/atom.py", line 49, in __init__
    self.args = [Atom.cast_to_const(arg) for arg in args]
  File "/home/ncim/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/atoms/atom.py", line 49, in <listcomp>
    self.args = [Atom.cast_to_const(arg) for arg in args]
  File "/home/ncim/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/expressions/expression.py", line 507, in cast_to_const
    return expr if isinstance(expr, Expression) else cvxtypes.constant()(expr)
  File "/home/ncim/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/expressions/constants/constant.py", line 58, in __init__
    super(Constant, self).__init__(intf.shape(self.value))
  File "/home/ncim/anaconda3/envs/lcs/lib/python3.9/site-packages/cvxpy/expressions/leaf.py", line 108, in __init__
    raise ValueError("Invalid dimensions %s." % (shape,))
ValueError: Invalid dimensions (0, 29).
[Wed Jan 10 12:59:28 2024]
Error in rule decompose:
    jobid: 1
    output: outputs/decompose/mypool.status, outputs/decompose/mypool.out
    shell:
        python scripts/vg-decompose.py -m outputs/variants_table/pango-markers-table.tsv -p outputs/variants_table/pool_samples_mypool.tsv -o outputs/decompose/mypool.out -s outputs/decompose/mypool.status --threads 30
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job decompose since they might be corrupted:
outputs/decompose/mypool.status, outputs/decompose/mypool.out
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-01-10T123811.796337.snakemake.log

**Comment by rvalieris** [comment]
Hello,

double check the files: 
 `outputs/variants_table/pango-markers-table.tsv` and 
`outputs/variants_table/pool_samples_mypool.tsv`

to make sure they were generated properly.
